/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF} from '@react-three/drei/useGLTF';


export default function Model(props) {
 
  const group = useRef()
  const { nodes, materials} = useGLTF('/squirrel.glb')
 
  
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh 
          geometry={nodes.Plane155.geometry} 
          material={materials['Material.010']} 
          position={[-10,32,25]} 
          />
    </group>
  )
}


useGLTF.preload('/squirrel.glb')
