/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import { Interaction } from 'three.interaction';


export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/toucan.gltf')

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Plane047.geometry} material={materials['Material.020']} position={[-10, 35, -25]} />
    </group>
  )
}



useGLTF.preload('/toucan.gltf')
