/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';


export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/tree.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} >
        <mesh geometry={nodes.Tree_1.geometry} material={materials['trunk color']} position={[28,-1,30]} scale={[1.5,1.5,1.5]}/>
        <mesh geometry={nodes.Tree_2.geometry} material={materials['branch color.001']} position={[28,-1,30]} scale={[1.5,1.5,1.5]} />
        <mesh geometry={nodes.Tree_3.geometry} material={materials['branch color']} position={[28,-1,30]} scale={[1.5,1.5,1.5]}/>
        <mesh geometry={nodes.Tree_4.geometry} material={materials['branch color.003']} position={[28,-1,30]} scale={[1.5,1.5,1.5]}/>
      </group>
    </group>
  )
}

useGLTF.preload('/tree.glb')
